"""
Stealth script generation.

Playwright can set the user-agent, viewport, locale, timezone and proxy at the
context level, but a number of high-signal values live inside the page and have
to be patched there. This module builds a single JavaScript init script tailored
to a fingerprint, which the launcher injects before any page code runs via
``add_init_script``.

The patches here mirror the well-known, publicly documented evasions used by
anti-detect browsers (and puppeteer/playwright stealth plugins). The goal is that
the in-page values agree with the context-level values *and* don't carry the
tell-tale traces of an automated browser:

  * ``navigator.webdriver`` reads ``false`` and looks native (defined on the
    prototype, not as an own property);
  * ``window.chrome`` exists with a ``runtime`` stub;
  * ``navigator.plugins`` / ``mimeTypes`` report the modern Chrome PDF set
    instead of an empty list;
  * ``navigator.permissions.query`` agrees with ``Notification.permission``;
  * platform, hardwareConcurrency, deviceMemory, languages, WebGL vendor/renderer
    match the chosen device;
  * ``document.fonts.check`` answers from the archetype's real font set, so font
    probing can't place a "Windows" browser on a Mac;
  * ``enumerateDevices`` reports the profile's camera/microphone count with
    seeded, stable device ids;
  * canvas, audio and ClientRects noise are seeded so they stay stable per
    profile — the same identity looks identical on every launch, and different
    from every other profile;
  * patched functions report native ``toString()`` so they can't be spotted.

Kept intentionally readable so contributors can audit exactly what is spoofed.
"""

from __future__ import annotations

import json

from .models import Fingerprint


def build_init_script(fp: Fingerprint) -> str:
    """Return a JS string that patches a page to match ``fp``."""
    cfg = {
        "platform": fp.platform,
        "uaPlatform": fp.ch_platform.strip('"'),
        "isMobile": fp.is_mobile,
        "chromeMajor": int(fp.chrome_version.split(".")[0]),
        "hardwareConcurrency": fp.hardware_concurrency,
        "deviceMemory": fp.device_memory,
        "languages": fp.languages,
        "webglVendor": fp.webgl_vendor,
        "webglRenderer": fp.webgl_renderer,
        "seed": fp.seed,
        "fonts": fp.fonts,
        "cameras": fp.cameras,
        "microphones": fp.microphones,
        "webrtc": fp.webrtc,
    }
    cfg_json = json.dumps(cfg)

    return (
        "(() => {\n"
        f"  const cfg = {cfg_json};\n"
        "\n"
        "  // Make an overridden function report native code, so its toString()\n"
        "  // doesn't reveal the patch.\n"
        "  const nativeStr = Function.prototype.toString;\n"
        "  const masked = new WeakMap();\n"
        "  const asNative = (fn, name) => {\n"
        "    masked.set(fn, name || fn.name || '');\n"
        "    return fn;\n"
        "  };\n"
        "  const toStringProxy = new Proxy(nativeStr, {\n"
        "    apply(target, thisArg, args) {\n"
        "      if (masked.has(thisArg)) return `function ${masked.get(thisArg)}() { [native code] }`;\n"
        "      return Reflect.apply(target, thisArg, args);\n"
        "    },\n"
        "  });\n"
        "  // eslint-disable-next-line no-extend-native\n"
        "  Function.prototype.toString = toStringProxy;\n"
        "\n"
        "  const define = (obj, prop, getter) => {\n"
        "    try {\n"
        "      Object.defineProperty(obj, prop, { get: asNative(getter, `get ${prop}`), configurable: true, enumerable: true });\n"
        "    } catch (e) {}\n"
        "  };\n"
        "\n"
        "  // --- webdriver: false, and defined on the prototype like real Chrome ---\n"
        "  try { delete Object.getPrototypeOf(navigator).webdriver; } catch (e) {}\n"
        "  try { delete navigator.webdriver; } catch (e) {}\n"
        "  define(Navigator.prototype, 'webdriver', () => false);\n"
        "\n"
        "  // --- Navigator basics ---\n"
        "  define(Navigator.prototype, 'platform', () => cfg.platform);\n"
        "  define(Navigator.prototype, 'hardwareConcurrency', () => cfg.hardwareConcurrency);\n"
        "  define(Navigator.prototype, 'deviceMemory', () => cfg.deviceMemory);\n"
        "  define(Navigator.prototype, 'languages', () => Object.freeze(cfg.languages.slice()));\n"
        "\n"
        "  // --- window.chrome (present on real Chrome, missing under automation) ---\n"
        "  try {\n"
        "    if (!window.chrome) window.chrome = {};\n"
        "    if (!window.chrome.runtime) window.chrome.runtime = {};\n"
        "    if (!window.chrome.app) window.chrome.app = { isInstalled: false };\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- Plugins & mimeTypes ---\n"
        "  // Headed Chrome already exposes the authentic PDF PluginArray, so we\n"
        "  // only synthesize one when the list is empty (typically headless), and\n"
        "  // we wire up the real prototypes/tags so it still reads as native.\n"
        "  try {\n"
        "    if (navigator.plugins.length === 0 &&\n"
        "        window.PluginArray && window.MimeTypeArray && window.Plugin && window.MimeType) {\n"
        "      const pdfNames = [\n"
        "        'PDF Viewer', 'Chrome PDF Viewer', 'Chromium PDF Viewer',\n"
        "        'Microsoft Edge PDF Viewer', 'WebKit built-in PDF',\n"
        "      ];\n"
        "      const mkMime = (type) => {\n"
        "        const m = { type, suffixes: 'pdf', description: 'Portable Document Format' };\n"
        "        Object.setPrototypeOf(m, MimeType.prototype);\n"
        "        return m;\n"
        "      };\n"
        "      const mimes = [mkMime('application/pdf'), mkMime('text/pdf')];\n"
        "      const mkArr = (items, proto, key) => {\n"
        "        const arr = {};\n"
        "        items.forEach((it, i) => { arr[i] = it; });\n"
        "        Object.defineProperty(arr, 'length', { value: items.length, enumerable: false });\n"
        "        arr.item = asNative((i) => items[i] || null, 'item');\n"
        "        arr.namedItem = asNative((n) => items.find((x) => x[key] === n) || null, 'namedItem');\n"
        "        Object.setPrototypeOf(arr, proto);\n"
        "        return arr;\n"
        "      };\n"
        "      const plugins = pdfNames.map((name) => {\n"
        "        const p = { name, filename: 'internal-pdf-viewer', description: 'Portable Document Format' };\n"
        "        mimes.forEach((m, i) => { p[i] = m; });\n"
        "        Object.defineProperty(p, 'length', { value: mimes.length, enumerable: false });\n"
        "        p.item = asNative((i) => mimes[i] || null, 'item');\n"
        "        p.namedItem = asNative((t) => mimes.find((m) => m.type === t) || null, 'namedItem');\n"
        "        Object.setPrototypeOf(p, Plugin.prototype);\n"
        "        return p;\n"
        "      });\n"
        "      const pluginArray = mkArr(plugins, PluginArray.prototype, 'name');\n"
        "      const mimeArray = mkArr(mimes, MimeTypeArray.prototype, 'type');\n"
        "      define(Navigator.prototype, 'plugins', () => pluginArray);\n"
        "      define(Navigator.prototype, 'mimeTypes', () => mimeArray);\n"
        "    }\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- permissions.query agrees with Notification.permission ---\n"
        "  try {\n"
        "    const orig = navigator.permissions.query.bind(navigator.permissions);\n"
        "    navigator.permissions.query = asNative(function query(params) {\n"
        "      if (params && params.name === 'notifications')\n"
        "        return Promise.resolve({ state: Notification.permission, onchange: null });\n"
        "      return orig(params);\n"
        "    }, 'query');\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- WebGL vendor / renderer (UNMASKED params 37445 / 37446) ---\n"
        "  const patchGL = (proto) => {\n"
        "    if (!proto) return;\n"
        "    const orig = proto.getParameter;\n"
        "    proto.getParameter = asNative(function getParameter(p) {\n"
        "      if (p === 37445) return cfg.webglVendor;\n"
        "      if (p === 37446) return cfg.webglRenderer;\n"
        "      return orig.call(this, p);\n"
        "    }, 'getParameter');\n"
        "  };\n"
        "  if (window.WebGLRenderingContext) patchGL(WebGLRenderingContext.prototype);\n"
        "  if (window.WebGL2RenderingContext) patchGL(WebGL2RenderingContext.prototype);\n"
        "\n"
        "  // --- Deterministic noise ---\n"
        "  // Every noise source draws from a PRNG restarted from the profile seed,\n"
        "  // never from a single advancing stream. That matters: on a real machine\n"
        "  // reading the same canvas twice gives the same bytes, so noise that\n"
        "  // changes per call is itself a detection signal (CreepJS checks for it).\n"
        "  const mkRnd = (seed) => {\n"
        "    let s = (seed >>> 0) || 1;\n"
        "    return () => { s = (s * 1664525 + 1013904223) >>> 0; return s / 4294967296; };\n"
        "  };\n"
        "  const rnd = mkRnd(cfg.seed);   // init-time draws (device ids, rect jitter)\n"
        "\n"
        "  const origToDataURL = HTMLCanvasElement.prototype.toDataURL;\n"
        "  HTMLCanvasElement.prototype.toDataURL = asNative(function toDataURL(...args) {\n"
        "    try {\n"
        "      if (this.getContext('2d') && this.width && this.height) {\n"
        "        // Noise goes on a throwaway copy, never the caller's canvas: the\n"
        "        // page keeps its real pixels and repeated reads stay identical.\n"
        "        const copy = document.createElement('canvas');\n"
        "        copy.width = this.width;\n"
        "        copy.height = this.height;\n"
        "        const cctx = copy.getContext('2d');\n"
        "        cctx.drawImage(this, 0, 0);\n"
        "        // Seed from the profile *and* the canvas size, so the same drawing\n"
        "        // always yields the same pixels for this profile.\n"
        "        const r = mkRnd(cfg.seed ^ (this.width * 73856093) ^ (this.height * 19349663));\n"
        "        const img = cctx.getImageData(0, 0, copy.width, copy.height);\n"
        "        for (let i = 0; i < img.data.length; i += 4) {\n"
        "          if (r() < 0.02) {\n"
        "            img.data[i]   ^= (r() * 2) | 0;\n"
        "            img.data[i+1] ^= (r() * 2) | 0;\n"
        "            img.data[i+2] ^= (r() * 2) | 0;\n"
        "          }\n"
        "        }\n"
        "        cctx.putImageData(img, 0, 0);\n"
        "        return origToDataURL.apply(copy, args);\n"
        "      }\n"
        "    } catch (e) {}\n"
        "    return origToDataURL.apply(this, args);\n"
        "  }, 'toDataURL');\n"
        "\n"
        "  // --- Installed fonts ---\n"
        "  // Font probing asks 'can you render X?'. Answer from the archetype's\n"
        "  // real font set so the reply matches the OS we claim to be.\n"
        "  try {\n"
        "    if (cfg.fonts.length && document.fonts && document.fonts.check) {\n"
        "      const installed = new Set(cfg.fonts.map((f) => f.toLowerCase()));\n"
        "      const generic = new Set(['serif', 'sans-serif', 'monospace', 'cursive',\n"
        "                               'fantasy', 'system-ui', 'ui-sans-serif', 'ui-serif',\n"
        "                               'ui-monospace', 'ui-rounded', '-apple-system']);\n"
        "      const origCheck = document.fonts.check.bind(document.fonts);\n"
        "      document.fonts.check = asNative(function check(font, text) {\n"
        "        try {\n"
        "          // font looks like '12px \"Segoe UI\"' — pull out the family.\n"
        "          const family = String(font).replace(/^\\s*[\\w.]+\\s+/, '')\n"
        "                                     .replace(/[\"']/g, '').split(',')[0].trim();\n"
        "          const key = family.toLowerCase();\n"
        "          if (generic.has(key)) return origCheck(font, text);\n"
        "          return installed.has(key);\n"
        "        } catch (e) { return origCheck(font, text); }\n"
        "      }, 'check');\n"
        "    }\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- Media devices (cameras / microphones) ---\n"
        "  // Ids are derived from the seed so they stay stable for this profile.\n"
        "  try {\n"
        "    if (navigator.mediaDevices && navigator.mediaDevices.enumerateDevices) {\n"
        "      const hex = (n) => {\n"
        "        let out = '';\n"
        "        for (let i = 0; i < n; i++) out += Math.floor(rnd() * 16).toString(16);\n"
        "        return out;\n"
        "      };\n"
        "      // MediaDeviceInfo exposes its fields as prototype getters, so the\n"
        "      // values have to come from there too — an object with own\n"
        "      // properties would be the wrong shape and easy to spot.\n"
        "      const values = new WeakMap();\n"
        "      const proto = MediaDeviceInfo.prototype;\n"
        "      for (const key of ['deviceId', 'kind', 'label', 'groupId']) {\n"
        "        const desc = Object.getOwnPropertyDescriptor(proto, key);\n"
        "        if (!desc || !desc.get) continue;\n"
        "        const origGet = desc.get;\n"
        "        Object.defineProperty(proto, key, {\n"
        "          get: asNative(function () {\n"
        "            const own = values.get(this);\n"
        "            return own ? own[key] : origGet.call(this);\n"
        "          }, `get ${key}`),\n"
        "          enumerable: desc.enumerable, configurable: true,\n"
        "        });\n"
        "      }\n"
        "      const mkDevice = (kind) => {\n"
        "        // Only inputs are InputDeviceInfo; speakers stay MediaDeviceInfo.\n"
        "        const base = (kind !== 'audiooutput' && window.InputDeviceInfo)\n"
        "          ? InputDeviceInfo.prototype : proto;\n"
        "        const dev = Object.create(base);\n"
        "        values.set(dev, { deviceId: hex(64), kind, label: '', groupId: hex(64) });\n"
        "        return dev;\n"
        "      };\n"
        "      const build = () => {\n"
        "        const list = [];\n"
        "        for (let i = 0; i < cfg.cameras; i++) list.push(mkDevice('videoinput'));\n"
        "        for (let i = 0; i < cfg.microphones; i++) list.push(mkDevice('audioinput'));\n"
        "        // A machine with a microphone almost always has an output too.\n"
        "        if (cfg.microphones) list.push(mkDevice('audiooutput'));\n"
        "        return list;\n"
        "      };\n"
        "      const devices = build();\n"
        "      navigator.mediaDevices.enumerateDevices = asNative(\n"
        "        function enumerateDevices() { return Promise.resolve(devices.slice()); },\n"
        "        'enumerateDevices');\n"
        "    }\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- ClientRects: sub-pixel noise, seeded and stable ---\n"
        "  // Real machines differ by fractions of a pixel; identical rects across\n"
        "  // profiles are the giveaway, so each profile gets its own tiny offset.\n"
        "  try {\n"
        "    const jitter = (rnd() - 0.5) * 0.0002;\n"
        "    const nudge = (v) => (typeof v === 'number' && v !== 0 ? v + v * jitter : v);\n"
        "    const patchRect = (proto, name) => {\n"
        "      const orig = proto[name];\n"
        "      if (!orig) return;\n"
        "      proto[name] = asNative(function (...args) {\n"
        "        const r = orig.apply(this, args);\n"
        "        if (name === 'getClientRects') {\n"
        "          for (const rect of r) shift(rect);\n"
        "          return r;\n"
        "        }\n"
        "        return shift(r);\n"
        "      }, name);\n"
        "    };\n"
        "    const shift = (r) => {\n"
        "      if (!r) return r;\n"
        "      const out = { x: nudge(r.x), y: nudge(r.y), width: nudge(r.width),\n"
        "                    height: nudge(r.height), top: nudge(r.top), right: nudge(r.right),\n"
        "                    bottom: nudge(r.bottom), left: nudge(r.left) };\n"
        "      for (const k of Object.keys(out)) {\n"
        "        try { Object.defineProperty(r, k, { get: asNative(() => out[k], `get ${k}`), configurable: true }); }\n"
        "        catch (e) {}\n"
        "      }\n"
        "      return r;\n"
        "    };\n"
        "    patchRect(Element.prototype, 'getBoundingClientRect');\n"
        "    patchRect(Element.prototype, 'getClientRects');\n"
        "    patchRect(Range.prototype, 'getBoundingClientRect');\n"
        "  } catch (e) {}\n"
        "\n"
        "  // --- Audio context: seeded noise, restarted per read so it stays stable ---\n"
        "  try {\n"
        "    if (window.AnalyserNode) {\n"
        "      const origFreq = AnalyserNode.prototype.getFloatFrequencyData;\n"
        "      AnalyserNode.prototype.getFloatFrequencyData = asNative(\n"
        "        function getFloatFrequencyData(array) {\n"
        "          const out = origFreq.apply(this, arguments);\n"
        "          const r = mkRnd(cfg.seed ^ 0x5eed1);\n"
        "          for (let i = 0; i < array.length; i += 100) array[i] += (r() - 0.5) * 1e-7;\n"
        "          return out;\n"
        "        }, 'getFloatFrequencyData');\n"
        "    }\n"
        "    if (window.AudioBuffer) {\n"
        "      // getChannelData hands back the live buffer, so noise it once and\n"
        "      // remember it — adding on every call would make the value drift.\n"
        "      const noised = new WeakSet();\n"
        "      const origGet = AudioBuffer.prototype.getChannelData;\n"
        "      AudioBuffer.prototype.getChannelData = asNative(function getChannelData(ch) {\n"
        "        const data = origGet.call(this, ch);\n"
        "        if (!noised.has(data)) {\n"
        "          noised.add(data);\n"
        "          const r = mkRnd(cfg.seed ^ 0x5eed2 ^ (ch | 0));\n"
        "          for (let i = 0; i < data.length; i += 500) data[i] += (r() - 0.5) * 1e-7;\n"
        "        }\n"
        "        return data;\n"
        "      }, 'getChannelData');\n"
        "    }\n"
        "  } catch (e) {}\n"
        "\n"
        "  // ---- WebRTC -------------------------------------------------\n"
        "  // Chromium's --force-webrtc-ip-handling-policy is the first line of\n"
        "  // defence, but it does not reliably stop ICE from offering a public\n"
        "  // address that is not the proxy's, which links the session straight\n"
        "  // back to the real IP. Private and mDNS candidates are deliberately left\n"
        "  // alone: a real browser behind NAT offers those, so stripping them would\n"
        "  // be its own tell.\n"
        "  try {\n"
        "    if (cfg.webrtc === 'disabled') {\n"
        "      for (const k of ['RTCPeerConnection', 'webkitRTCPeerConnection',\n"
        "                       'RTCDataChannel', 'mozRTCPeerConnection']) {\n"
        "        try { delete window[k]; } catch (e) { window[k] = undefined; }\n"
        "      }\n"
        "    } else if (cfg.webrtc !== 'real' && window.RTCPeerConnection) {\n"
        "      const RTC = window.RTCPeerConnection;\n"
        "      const ipOf = (line) => {\n"
        "        const m = /(\\d{1,3}(?:\\.\\d{1,3}){3})/.exec(line || '');\n"
        "        return m ? m[1] : null;\n"
        "      };\n"
        "      // Anything not routable on the public internet is safe to keep.\n"
        "      const safe = (line) => {\n"
        "        if (/\\.local\\b/.test(line)) return true;   // mDNS, already anonymous\n"
        "        const ip = ipOf(line);\n"
        "        if (!ip) return true;                        // IPv6 or no address at all\n"
        "        return /^(10\\.|127\\.|0\\.|169\\.254\\.|192\\.168\\.|172\\.(1[6-9]|2\\d|3[01])\\.)/.test(ip);\n"
        "      };\n"
        "      const scrub = (sdp) => typeof sdp === 'string'\n"
        "        ? sdp.split(/\\r?\\n/).filter(l => !/^a=candidate:/.test(l) || safe(l)).join('\\r\\n')\n"
        "        : sdp;\n"
        "      const drop = (ev) => {\n"
        "        const c = ev && ev.candidate && ev.candidate.candidate;\n"
        "        return !!c && !safe(c);   // keep the null end-of-candidates event\n"
        "      };\n"
        "\n"
        "      const wrapped = new WeakMap();\n"
        "      const origAdd = RTC.prototype.addEventListener;\n"
        "      RTC.prototype.addEventListener = asNative(function addEventListener(type, fn) {\n"
        "        if (type === 'icecandidate' && typeof fn === 'function') {\n"
        "          let w = wrapped.get(fn);\n"
        "          if (!w) {\n"
        "            w = function (ev) { if (!drop(ev)) return fn.apply(this, arguments); };\n"
        "            wrapped.set(fn, w);\n"
        "          }\n"
        "          return origAdd.call(this, type, w, arguments[2]);\n"
        "        }\n"
        "        return origAdd.apply(this, arguments);\n"
        "      }, 'addEventListener');\n"
        "      const origRemove = RTC.prototype.removeEventListener;\n"
        "      RTC.prototype.removeEventListener = asNative(function removeEventListener(type, fn) {\n"
        "        if (type === 'icecandidate' && wrapped.has(fn)) {\n"
        "          return origRemove.call(this, type, wrapped.get(fn), arguments[2]);\n"
        "        }\n"
        "        return origRemove.apply(this, arguments);\n"
        "      }, 'removeEventListener');\n"
        "\n"
        "      const onice = Object.getOwnPropertyDescriptor(RTC.prototype, 'onicecandidate');\n"
        "      if (onice && onice.set) {\n"
        "        const handlers = new WeakMap();\n"
        "        Object.defineProperty(RTC.prototype, 'onicecandidate', {\n"
        "          configurable: true,\n"
        "          enumerable: onice.enumerable,\n"
        "          get() { return handlers.get(this) || null; },\n"
        "          set(fn) {\n"
        "            handlers.set(this, fn);\n"
        "            onice.set.call(this, typeof fn === 'function'\n"
        "              ? function (ev) { if (!drop(ev)) return fn.apply(this, arguments); }\n"
        "              : fn);\n"
        "          },\n"
        "        });\n"
        "      }\n"
        "\n"
        "      // Candidates also travel inside the SDP, so a page that never listens\n"
        "      // for the event can still read them off the description.\n"
        "      for (const prop of ['localDescription', 'currentLocalDescription',\n"
        "                          'pendingLocalDescription']) {\n"
        "        const d = Object.getOwnPropertyDescriptor(RTC.prototype, prop);\n"
        "        if (!d || !d.get) continue;\n"
        "        Object.defineProperty(RTC.prototype, prop, {\n"
        "          configurable: true,\n"
        "          enumerable: d.enumerable,\n"
        "          get() {\n"
        "            const desc = d.get.call(this);\n"
        "            if (!desc) return desc;\n"
        "            const sdp = scrub(desc.sdp);\n"
        "            return { type: desc.type, sdp, toJSON: () => ({ type: desc.type, sdp }) };\n"
        "          },\n"
        "        });\n"
        "      }\n"
        "      for (const m of ['createOffer', 'createAnswer']) {\n"
        "        const orig = RTC.prototype[m];\n"
        "        if (!orig) continue;\n"
        "        RTC.prototype[m] = asNative(function () {\n"
        "          const out = orig.apply(this, arguments);\n"
        "          return out && typeof out.then === 'function'\n"
        "            ? out.then(d => (d && d.sdp ? { type: d.type, sdp: scrub(d.sdp) } : d))\n"
        "            : out;\n"
        "        }, m);\n"
        "      }\n"
        "    }\n"
        "  } catch (e) {}\n"
        "})();\n"
    )
